// <auto-generated />
using System;
using MEngine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MEngine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MEngineDbContext))]
    partial class MEngineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("MEngine.Domain.Entities.AgentConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentName")
                        .IsUnique();

                    b.ToTable("AgentConfigurations", (string)null);
                });

            modelBuilder.Entity("MEngine.Domain.Entities.CommitResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExecutionRunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionRunId");

                    b.ToTable("CommitResults", (string)null);
                });

            modelBuilder.Entity("MEngine.Domain.Entities.ExecutionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentIteration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxIterations")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyPipeline")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputFolder")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentConfigurationId");

                    b.ToTable("ExecutionRuns", (string)null);
                });

            modelBuilder.Entity("MEngine.Domain.Entities.ExecutionStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExecutionRunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionRunId");

                    b.ToTable("ExecutionSteps", (string)null);
                });

            modelBuilder.Entity("MEngine.Domain.Entities.FinalReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExecutionRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalHtmlReportPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalReportPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionRunId");

                    b.ToTable("FinalReports", (string)null);
                });

            modelBuilder.Entity("MEngine.Domain.Entities.MutationReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExecutionRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonReportPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MutationScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThresholdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tool")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionRunId");

                    b.ToTable("MutationReports", (string)null);
                });

            modelBuilder.Entity("MEngine.Domain.Entities.PipelineNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExecutionRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionRunId");

                    b.ToTable("PipelineNotifications", (string)null);
                });

            modelBuilder.Entity("MEngine.Domain.Entities.RepositoryAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedFilesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExecutionRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MasterPromptApplied")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileSummary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepoSummary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TestFramework")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionRunId");

                    b.ToTable("RepositoryAnalyses", (string)null);
                });

            modelBuilder.Entity("MEngine.Domain.Entities.TestDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Decision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExecutionRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetFilesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionRunId");

                    b.ToTable("TestDecisions", (string)null);
                });

            modelBuilder.Entity("MEngine.Domain.Entities.TestRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExecutionRunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Failed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Iteration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Passed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionRunId");

                    b.ToTable("TestRuns", (string)null);
                });

            modelBuilder.Entity("MEngine.Domain.Entities.CommitResult", b =>
                {
                    b.HasOne("MEngine.Domain.Entities.ExecutionRun", "ExecutionRun")
                        .WithMany()
                        .HasForeignKey("ExecutionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionRun");
                });

            modelBuilder.Entity("MEngine.Domain.Entities.ExecutionRun", b =>
                {
                    b.HasOne("MEngine.Domain.Entities.AgentConfiguration", "AgentConfiguration")
                        .WithMany()
                        .HasForeignKey("AgentConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentConfiguration");
                });

            modelBuilder.Entity("MEngine.Domain.Entities.ExecutionStep", b =>
                {
                    b.HasOne("MEngine.Domain.Entities.ExecutionRun", "ExecutionRun")
                        .WithMany("Steps")
                        .HasForeignKey("ExecutionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionRun");
                });

            modelBuilder.Entity("MEngine.Domain.Entities.FinalReport", b =>
                {
                    b.HasOne("MEngine.Domain.Entities.ExecutionRun", "ExecutionRun")
                        .WithMany()
                        .HasForeignKey("ExecutionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionRun");
                });

            modelBuilder.Entity("MEngine.Domain.Entities.MutationReport", b =>
                {
                    b.HasOne("MEngine.Domain.Entities.ExecutionRun", "ExecutionRun")
                        .WithMany()
                        .HasForeignKey("ExecutionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionRun");
                });

            modelBuilder.Entity("MEngine.Domain.Entities.PipelineNotification", b =>
                {
                    b.HasOne("MEngine.Domain.Entities.ExecutionRun", "ExecutionRun")
                        .WithMany()
                        .HasForeignKey("ExecutionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionRun");
                });

            modelBuilder.Entity("MEngine.Domain.Entities.RepositoryAnalysis", b =>
                {
                    b.HasOne("MEngine.Domain.Entities.ExecutionRun", "ExecutionRun")
                        .WithMany()
                        .HasForeignKey("ExecutionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionRun");
                });

            modelBuilder.Entity("MEngine.Domain.Entities.TestDecision", b =>
                {
                    b.HasOne("MEngine.Domain.Entities.ExecutionRun", "ExecutionRun")
                        .WithMany()
                        .HasForeignKey("ExecutionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionRun");
                });

            modelBuilder.Entity("MEngine.Domain.Entities.TestRun", b =>
                {
                    b.HasOne("MEngine.Domain.Entities.ExecutionRun", "ExecutionRun")
                        .WithMany()
                        .HasForeignKey("ExecutionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionRun");
                });

            modelBuilder.Entity("MEngine.Domain.Entities.ExecutionRun", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
